-- Seed: pesquisas Doxa para Deputado Federal e Estadual (PA 2026)
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqdep-01', 'Deputado Federal', 1, 'estimulada', 'Atuais deputados', 'Doxa', 'PA-06056/2026', '2026-03-25 00:00:00', '2026-03-31 00:00:00', '2026-03-31 00:00:00', 2000, 3.1, 95, 'Data exibida = fim do campo. Carga automática 25/08/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r0', 'pqdep-01', 'Renilce Nicodemos', 'MDB', 9.68, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r1', 'pqdep-01', 'Priante', 'MDB', 6.16, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r2', 'pqdep-01', 'Júnior Ferrari', 'PSD', 4.79, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r3', 'pqdep-01', 'Andreia Siqueira', 'MDB', 4.74, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r4', 'pqdep-01', 'Dra. Alessandra Haber', NULL, 4.63, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r5', 'pqdep-01', 'Delegado Kaveira', NULL, 3.21, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r6', 'pqdep-01', 'Celso Sabino', NULL, 2.84, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r7', 'pqdep-01', 'Airton Faleiro', 'PT', 2.79, 7);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r8', 'pqdep-01', 'Joaquim Passarinho', NULL, 2.68, 8);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r9', 'pqdep-01', 'Keniston Braga', 'MDB', 2.58, 9);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r10', 'pqdep-01', 'Olival Marques', NULL, 2.53, 10);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r11', 'pqdep-01', 'Antonio Doido', NULL, 2.11, 11);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r12', 'pqdep-01', 'Dilvanda Faro', NULL, 2, 12);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r13', 'pqdep-01', 'Henderson Pinto', NULL, 1.42, 13);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r14', 'pqdep-01', 'Raimundo Santos', NULL, 1.21, 14);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r15', 'pqdep-01', 'NS/SR', NULL, 38.05, 15);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-01-r16', 'pqdep-01', 'Brancos/Nulos', NULL, 8.58, 16);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqdep-02', 'Deputado Federal', 1, 'estimulada', 'Novos nomes', 'Doxa', 'PA-06056/2026', '2026-03-25 00:00:00', '2026-03-31 00:00:00', '2026-03-31 00:00:00', 2000, 3.1, 95, 'Data exibida = fim do campo. Carga automática 25/08/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r0', 'pqdep-02', 'Bob Flay', NULL, 11.49, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r1', 'pqdep-02', 'Jader Filho', 'MDB', 10.64, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r2', 'pqdep-02', 'Cássio Andrade', 'MDB', 3.96, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r3', 'pqdep-02', 'Delegada Érica Sabino', NULL, 3.21, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r4', 'pqdep-02', 'Edmilson Rodrigues', 'PSOL', 3.05, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r5', 'pqdep-02', 'Pioneiro', 'REPUBLICANOS', 2.78, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r6', 'pqdep-02', 'Adriana Almeida', 'MDB', 1.98, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r7', 'pqdep-02', 'Rogério Barra', 'PL', 1.28, 7);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r8', 'pqdep-02', 'Evandro Garla', 'REPUBLICANOS', 1.23, 8);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r9', 'pqdep-02', 'Adriano Coelho', NULL, 1.12, 9);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r10', 'pqdep-02', 'Cynthia Charone', NULL, 1.12, 10);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r11', 'pqdep-02', 'Dr. Igor Parente', NULL, 1.1, 11);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r12', 'pqdep-02', 'Adamor Bittencourt', NULL, 0.96, 12);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r13', 'pqdep-02', 'Prof. Alfredo Costa', NULL, 0.91, 13);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r14', 'pqdep-02', 'Lu Ogawa', NULL, 0.91, 14);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r15', 'pqdep-02', 'Leila Palheta', NULL, 0.8, 15);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r16', 'pqdep-02', 'Vivi Reis', NULL, 0.8, 16);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r17', 'pqdep-02', 'Paulo Gaya', NULL, 0.75, 17);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r18', 'pqdep-02', 'Chapadinha', NULL, 0.75, 18);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r19', 'pqdep-02', 'Enio Monteiro', NULL, 0.72, 19);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r20', 'pqdep-02', 'Yuri Faro', NULL, 0.69, 20);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r21', 'pqdep-02', 'Nazaré Lima', NULL, 0.64, 21);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r22', 'pqdep-02', 'Marcelo Pierre', NULL, 0.62, 22);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r23', 'pqdep-02', 'Carlos Maneschi', NULL, 0.59, 23);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r24', 'pqdep-02', 'Lena Ribeiro', NULL, 0.59, 24);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r25', 'pqdep-02', 'Lelio Costa', NULL, 0.43, 25);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r26', 'pqdep-02', 'NS/SR', NULL, 39.25, 26);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-02-r27', 'pqdep-02', 'Brancos/Nulos', NULL, 7.64, 27);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqdep-03', 'Deputado Estadual', 1, 'estimulada', 'Nomes atuais', 'Doxa', NULL, '2026-01-15 00:00:00', '2026-07-15 00:00:00', '2026-07-15 00:00:00', 10000, 3.1, 95, 'Consolidado de 6 rodadas (janeiro a julho/2026), 10.000 entrevistas nas 6 mesorregiões. Data exibida = fim do campo. Carga automática 25/08/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r0', 'pqdep-03', 'Chamonzinho', 'MDB', 4.48, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r1', 'pqdep-03', 'Coronel Neil', 'PL', 3.26, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r2', 'pqdep-03', 'Zeca Pirão', 'MDB', 3.13, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r3', 'pqdep-03', 'Dr. Wanderlan', 'MDB', 3.06, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r4', 'pqdep-03', 'Maria do Carmo', 'PT', 2.04, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r5', 'pqdep-03', 'Delegado Nilton Neves', 'PSD', 1.95, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r6', 'pqdep-03', 'Ana Cunha', 'MDB', 1.84, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r7', 'pqdep-03', 'Luth Rebelo', 'PP', 1.76, 7);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r8', 'pqdep-03', 'Erick Monteiro', 'MDB', 1.73, 8);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r9', 'pqdep-03', 'Dirceu Ten Caten', 'PT', 1.7, 9);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r10', 'pqdep-03', 'Angelo Ferrari', 'UNIÃO', 1.67, 10);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r11', 'pqdep-03', 'João Pingarilho', 'MDB', 1.6, 11);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r12', 'pqdep-03', 'Thiago Araújo', 'UNIÃO', 1.54, 12);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r13', 'pqdep-03', 'Iran Lima', 'MDB', 1.53, 13);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r14', 'pqdep-03', 'Lívia Duarte', 'PSOL', 1.52, 14);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r15', 'pqdep-03', 'Carlos Bordalo', 'PT', 1.46, 15);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r16', 'pqdep-03', 'Torrinho', 'REPUBLICANOS', 1.43, 16);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r17', 'pqdep-03', 'Paula Titan', 'PP', 1.43, 17);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r18', 'pqdep-03', 'Andreia Xarão', 'MDB', 1.18, 18);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r19', 'pqdep-03', 'Gustavo Sefer', 'PSD', 1.15, 19);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r20', 'pqdep-03', 'Aveilton Souza', 'PSD', 1.13, 20);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r21', 'pqdep-03', 'Cilene Couto', 'MDB', 1.11, 21);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r22', 'pqdep-03', 'Carlos Vinícius', 'MDB', 1.06, 22);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r23', 'pqdep-03', 'Ronie Silva', 'MDB', 0.99, 23);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r24', 'pqdep-03', 'Josué Paiva', 'REPUBLICANOS', 0.98, 24);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r25', 'pqdep-03', 'Eraldo Pimenta', 'MDB', 0.83, 25);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r26', 'pqdep-03', 'Wescley Tomaz', 'AVANTE', 0.75, 26);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r27', 'pqdep-03', 'Antonio Tonheiro', 'PT', 0.75, 27);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r28', 'pqdep-03', 'Elias Santiago', 'PT', 0.73, 28);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r29', 'pqdep-03', 'Diana Belo', 'UNIÃO', 0.65, 29);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r30', 'pqdep-03', 'Fábio Figueiras', 'PV', 0.51, 30);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r31', 'pqdep-03', 'Renato Oliveira', 'AVANTE', 0.51, 31);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r32', 'pqdep-03', 'Fábio Freitas', 'UNIÃO', 0.49, 32);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r33', 'pqdep-03', 'Vitor Dias', 'UNIÃO', 0.44, 33);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r34', 'pqdep-03', 'Martinho Carmona', 'MDB', 0.3, 34);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r35', 'pqdep-03', 'NS/SR', NULL, 41.89, 35);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-03-r36', 'pqdep-03', 'Brancos/Nulos', NULL, 8.06, 36);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqdep-04', 'Deputado Estadual', 1, 'estimulada', 'Novos nomes', 'Doxa', NULL, '2026-01-15 00:00:00', '2026-07-15 00:00:00', '2026-07-15 00:00:00', 10000, 3.1, 95, 'Consolidado de 6 rodadas (janeiro a julho/2026), 10.000 entrevistas nas 6 mesorregiões. Data exibida = fim do campo. Carga automática 25/08/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r0', 'pqdep-04', 'Elcione Barbalho', NULL, 6.3, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r1', 'pqdep-04', 'Jeferson Lima', NULL, 4.51, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r2', 'pqdep-04', 'JK do Povão', NULL, 2.51, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r3', 'pqdep-04', 'Juá Pará', NULL, 1.94, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r4', 'pqdep-04', 'Júnior da Saúde', NULL, 1.72, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r5', 'pqdep-04', 'Neném Albuquerque', NULL, 1.6, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r6', 'pqdep-04', 'Nay Barbalho', NULL, 1.53, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r7', 'pqdep-04', 'Miro Sanova', NULL, 1.5, 7);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r8', 'pqdep-04', 'Mayki Vilaça', NULL, 1.48, 8);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r9', 'pqdep-04', 'Renata Fonseca', NULL, 1.43, 9);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r10', 'pqdep-04', 'Zezinho Lima', NULL, 1.42, 10);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r11', 'pqdep-04', 'Elayne D''Almeida', NULL, 1.41, 11);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r12', 'pqdep-04', 'João Coelho', NULL, 1.34, 12);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r13', 'pqdep-04', 'Paola Abucater', NULL, 1.33, 13);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r14', 'pqdep-04', 'Prof. Diego', NULL, 1.21, 14);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r15', 'pqdep-04', 'Ary Nascimento', NULL, 1.21, 15);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r16', 'pqdep-04', 'Nélio Aguiar', NULL, 1.21, 16);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r17', 'pqdep-04', 'Marinor Brito', NULL, 1.15, 17);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r18', 'pqdep-04', 'Diely Silva', NULL, 1.15, 18);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r19', 'pqdep-04', 'Rafael Ribeiro', NULL, 1.11, 19);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r20', 'pqdep-04', 'João Salame', NULL, 1.03, 20);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r21', 'pqdep-04', 'Watanabe Filho', NULL, 0.95, 21);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r22', 'pqdep-04', 'Paulo Henrique', NULL, 0.9, 22);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r23', 'pqdep-04', 'Hilton Aguiar', NULL, 0.88, 23);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r24', 'pqdep-04', 'Alexandre Gomes', NULL, 0.76, 24);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r25', 'pqdep-04', 'Beto Andrade', NULL, 0.72, 25);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r26', 'pqdep-04', 'Macarrão', NULL, 0.67, 26);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r27', 'pqdep-04', 'Elielton Lira', NULL, 0.61, 27);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r28', 'pqdep-04', 'Rui Begot', NULL, 0.61, 28);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r29', 'pqdep-04', 'Adriene Hage', NULL, 0.53, 29);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r30', 'pqdep-04', 'Caio do Agro', NULL, 0.51, 30);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r31', 'pqdep-04', 'Sipriano Ferraz', NULL, 0.49, 31);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r32', 'pqdep-04', 'Janaina', NULL, 0.43, 32);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r33', 'pqdep-04', 'Leonardo Vale', NULL, 0.39, 33);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r34', 'pqdep-04', 'Mazinho Salomão', NULL, 0.38, 34);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r35', 'pqdep-04', 'Auricélia Arapium', NULL, 0.35, 35);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r36', 'pqdep-04', 'Marcos Brazão', NULL, 0.34, 36);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r37', 'pqdep-04', 'Hipólito', NULL, 0.31, 37);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r38', 'pqdep-04', 'Marisa Almeida', NULL, 0.24, 38);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r39', 'pqdep-04', 'Sidneya Leite', NULL, 0.22, 39);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r40', 'pqdep-04', 'Lanúzia Lobo', NULL, 0.21, 40);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r41', 'pqdep-04', 'Giordana Estrela', NULL, 0.21, 41);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r42', 'pqdep-04', 'Rodrigo Cunha', NULL, 0.2, 42);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r43', 'pqdep-04', 'Carol Silva', NULL, 0.2, 43);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r44', 'pqdep-04', 'Zé Geraldo', NULL, 0.15, 44);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r45', 'pqdep-04', 'Neyla Braga', NULL, 0.1, 45);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r46', 'pqdep-04', 'Fabrício Gama', NULL, 0.1, 46);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r47', 'pqdep-04', 'Coronel Firmino', NULL, 0.08, 47);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r48', 'pqdep-04', 'Raimundão', NULL, 0.08, 48);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r49', 'pqdep-04', 'NS/SR', NULL, 42.72, 49);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqdep-04-r50', 'pqdep-04', 'Brancos/Nulos', NULL, 7.57, 50);
