-- Seed: pesquisas 05-13/set/2026 (AtlasIntel PA, Doxa gov+dep federal, presidenciais)
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-01', 'Governador', 1, 'estimulada', NULL, 'AtlasIntel', 'PA-09626/2026', '2026-09-05 00:00:00', '2026-09-10 00:00:00', '2026-09-10 00:00:00', 1212, 3, 95, 'Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-01-r0', 'pqs2-01', 'Hana Ghassan', 'MDB', 48.5, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-01-r1', 'pqs2-01', 'Daniel Santos', 'PODE', 41.7, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-01-r2', 'pqs2-01', 'Araceli Lemos', 'PSOL', 1.5, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-01-r3', 'pqs2-01', 'José Moita', 'DEMOCRATA', 0.8, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-01-r4', 'pqs2-01', 'Outros', NULL, 0.7, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-01-r5', 'pqs2-01', 'Brancos/Nulos', NULL, 0.6, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-01-r6', 'pqs2-01', 'Não sabe', NULL, 6.1, 6);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-02', 'Governador', 1, 'estimulada', NULL, 'Doxa', NULL, '2026-09-08 00:00:00', '2026-09-12 00:00:00', '2026-09-12 00:00:00', 2000, 2.2, 95, 'Divulgação restrita aos líderes — demais candidatos/indecisos não publicados. Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-02-r0', 'pqs2-02', 'Hana Ghassan', 'MDB', 38.1, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-02-r1', 'pqs2-02', 'Daniel Santos', 'PODE', 32.6, 1);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-03', 'Governador', 2, 'estimulada', 'Hana Ghassan x Daniel Santos', 'AtlasIntel', 'PA-09626/2026', '2026-09-05 00:00:00', '2026-09-10 00:00:00', '2026-09-10 00:00:00', 1212, 3, 95, 'Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-03-r0', 'pqs2-03', 'Hana Ghassan', 'MDB', 50.2, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-03-r1', 'pqs2-03', 'Daniel Santos', 'PODE', 45.4, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-03-r2', 'pqs2-03', 'Brancos/Nulos', NULL, 1, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-03-r3', 'pqs2-03', 'Não sabe', NULL, 3.3, 3);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-04', 'Senador', 1, 'estimulada', NULL, 'AtlasIntel', 'PA-09626/2026', '2026-09-05 00:00:00', '2026-09-10 00:00:00', '2026-09-10 00:00:00', 1212, 3, 95, 'Disputa por 2 vagas. Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r0', 'pqs2-04', 'Helder Barbalho', 'MDB', 24.9, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r1', 'pqs2-04', 'Éder Mauro', 'PL', 18.1, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r2', 'pqs2-04', 'Zequinha Marinho', 'PODE', 15.1, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r3', 'pqs2-04', 'Chicão Melo', 'UNIÃO', 13.2, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r4', 'pqs2-04', 'Celso Sabino', 'PDT', 11.6, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r5', 'pqs2-04', 'Gizelle Freitas', 'PSOL', 1.7, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r6', 'pqs2-04', 'Conti', NULL, 1.1, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r7', 'pqs2-04', 'Lívia Noronha', 'SOLIDARIEDADE', 1.1, 7);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r8', 'pqs2-04', 'Outros', NULL, 1.1, 8);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r9', 'pqs2-04', 'Brancos/Nulos', NULL, 4.3, 9);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-04-r10', 'pqs2-04', 'Não sabe', NULL, 7.8, 10);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-05', 'Deputado Federal', 1, 'estimulada', 'Fatia dentro do partido', 'Doxa', 'PA-06964/2026', '2026-09-08 00:00:00', '2026-09-12 00:00:00', '2026-09-12 00:00:00', 2000, 3.1, 95, 'Percentual = fatia do candidato DENTRO do próprio partido (soma ~100% por partido; acumulado de 12.000 entrevistas em 2026). Projeção de cadeiras (17): MDB 6, PODE 3, PL 2, PSD 2, PT/PV/PCdoB 1, UNIÃO/PP 1, PSB 1, REPUBLICANOS 1. Registros: PA-06964, 06056, 00899, 07315, 01857, 06730/2026. Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r0', 'pqs2-05', 'Jader Filho', 'MDB', 25.19, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r1', 'pqs2-05', 'Renilce Nicodemos', 'MDB', 18.78, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r2', 'pqs2-05', 'Priante', 'MDB', 18.09, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r3', 'pqs2-05', 'Cássio Andrade', 'MDB', 9.35, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r4', 'pqs2-05', 'Delegada Érika Sabino', 'MDB', 8, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r5', 'pqs2-05', 'Adriana Almeida', 'MDB', 6.59, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r6', 'pqs2-05', 'Keniston Braga', 'MDB', 5.29, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r7', 'pqs2-05', 'Adriano Coelho', 'MDB', 4.23, 7);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r8', 'pqs2-05', 'Antonio Doido', 'MDB', 3.83, 8);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r9', 'pqs2-05', 'Paulo Bengston', 'MDB', 0.66, 9);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r10', 'pqs2-05', 'Delegado Kaveira', 'PL', 46.36, 10);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r11', 'pqs2-05', 'Rogério Barra', 'PL', 30.88, 11);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r12', 'pqs2-05', 'Joaquim Passarinho', 'PL', 20.21, 12);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r13', 'pqs2-05', 'Tingo Soares', 'PL', 1.7, 13);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r14', 'pqs2-05', 'Tati Lima', 'PL', 0.57, 14);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r15', 'pqs2-05', 'Feliciano Neto', 'PL', 0.19, 15);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r16', 'pqs2-05', 'Pacheco', 'PL', 0.09, 16);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r17', 'pqs2-05', 'Bob Fllay', 'PODE', 40.38, 17);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r18', 'pqs2-05', 'Dra. Alessandra Haber', 'PODE', 29.48, 18);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r19', 'pqs2-05', 'Adamor Bittencourt', 'PODE', 11.07, 19);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r20', 'pqs2-05', 'Olival Marques', 'PODE', 7.76, 20);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r21', 'pqs2-05', 'Chapadinha', 'PODE', 4.56, 21);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r22', 'pqs2-05', 'Marcelo Pierre', 'PODE', 3.32, 22);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r23', 'pqs2-05', 'Neném da Danysar', 'PODE', 3.02, 23);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r24', 'pqs2-05', 'Dr. Felipe', 'PODE', 0.36, 24);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r25', 'pqs2-05', 'Débora Abelha', 'PODE', 0.06, 25);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r26', 'pqs2-05', 'Júnior Ferrari', 'PSD', 51.57, 26);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r27', 'pqs2-05', 'Raimundo Santos', 'PSD', 15.7, 27);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r28', 'pqs2-05', 'Cynthia Charone', 'PSD', 10.58, 28);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r29', 'pqs2-05', 'Dr. Igor Parente', 'PSD', 9.8, 29);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r30', 'pqs2-05', 'Braz', 'PSD', 9.69, 30);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r31', 'pqs2-05', 'Pedrinho Borges', 'PSD', 1.35, 31);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r32', 'pqs2-05', 'Max Fera', 'PSD', 0.9, 32);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r33', 'pqs2-05', 'Luiz Rebelo', 'PSD', 0.36, 33);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r34', 'pqs2-05', 'Paulo Pinho', 'PSD', 0.07, 34);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r35', 'pqs2-05', 'Lena Pinto', 'UNIÃO/PP', 37.95, 35);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r36', 'pqs2-05', 'Henderson Pinto', 'UNIÃO/PP', 29.6, 36);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r37', 'pqs2-05', 'Lu Ogawa', 'UNIÃO/PP', 17.46, 37);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r38', 'pqs2-05', 'Engenheiro Diogo', 'UNIÃO/PP', 14.42, 38);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r39', 'pqs2-05', 'Prof. Diego', 'UNIÃO/PP', 0.57, 39);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r40', 'pqs2-05', 'Andreia Siqueira', 'PSB', 60.07, 40);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r41', 'pqs2-05', 'Úrsula Vidal', 'PSB', 10.19, 41);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r42', 'pqs2-05', 'Fábio Sousa', 'PSB', 9.49, 42);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r43', 'pqs2-05', 'Carol Resque', 'PSB', 7.99, 43);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r44', 'pqs2-05', 'Lulu das Comunidades', 'PSB', 7.06, 44);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r45', 'pqs2-05', 'Eliete Braga', 'PSB', 4.98, 45);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r46', 'pqs2-05', 'Alemão', 'PSB', 0.12, 46);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r47', 'pqs2-05', 'Carla Parente', 'PSB', 0.12, 47);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r48', 'pqs2-05', 'Airton Faleiro', 'PT/PV/PCdoB', 29.94, 48);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r49', 'pqs2-05', 'Dilvanda Faro', 'PT/PV/PCdoB', 25.56, 49);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r50', 'pqs2-05', 'Prof. Alfredo Costa', 'PT/PV/PCdoB', 11.3, 50);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r51', 'pqs2-05', 'Biga Kalahari', 'PT/PV/PCdoB', 11.02, 51);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r52', 'pqs2-05', 'Yuri Faro', 'PT/PV/PCdoB', 10.88, 52);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r53', 'pqs2-05', 'Paulo Gaya', 'PT/PV/PCdoB', 10.88, 53);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r54', 'pqs2-05', 'Rodrigo Moraes', 'PT/PV/PCdoB', 0.42, 54);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r55', 'pqs2-05', 'Pioneiro', 'REPUBLICANOS', 35.24, 55);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r56', 'pqs2-05', 'Evandro Garla', 'REPUBLICANOS', 33.25, 56);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r57', 'pqs2-05', 'Delegado Eguchi', 'REPUBLICANOS', 22.05, 57);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r58', 'pqs2-05', 'Tatagiba', 'REPUBLICANOS', 6.87, 58);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r59', 'pqs2-05', 'Bruna de Lima', 'REPUBLICANOS', 1.87, 59);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r60', 'pqs2-05', 'Ozorio Juvenil', 'REPUBLICANOS', 0.36, 60);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-05-r61', 'pqs2-05', 'Rita Pinho', 'REPUBLICANOS', 0.36, 61);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-06', 'Presidente', 1, 'estimulada', NULL, 'Datafolha', NULL, '2026-09-08 00:00:00', '2026-09-11 00:00:00', '2026-09-11 00:00:00', 2002, 2, 95, 'Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-06-r0', 'pqs2-06', 'Lula', 'PT', 39, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-06-r1', 'pqs2-06', 'Flávio Bolsonaro', 'PL', 35, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-06-r2', 'pqs2-06', 'Augusto Cury', 'AVANTE', 6, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-06-r3', 'pqs2-06', 'Ronaldo Caiado', 'PSD', 4, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-06-r4', 'pqs2-06', 'Renan Santos', 'MISSÃO', 3, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-06-r5', 'pqs2-06', 'Indecisos/Brancos', NULL, 10, 5);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-07', 'Presidente', 1, 'estimulada', NULL, 'Genial/Quaest', NULL, '2026-09-10 00:00:00', '2026-09-13 00:00:00', '2026-09-13 00:00:00', 2004, 2, 95, 'Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-07-r0', 'pqs2-07', 'Lula', 'PT', 36, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-07-r1', 'pqs2-07', 'Flávio Bolsonaro', 'PL', 31, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-07-r2', 'pqs2-07', 'Augusto Cury', 'AVANTE', 7, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-07-r3', 'pqs2-07', 'Renan Santos', 'MISSÃO', 4, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-07-r4', 'pqs2-07', 'Ronaldo Caiado', 'PSD', 4, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-07-r5', 'pqs2-07', 'Indecisos/Brancos', NULL, 17, 5);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-08', 'Presidente', 1, 'estimulada', NULL, 'Nexus/BTG Pactual', NULL, '2026-09-11 00:00:00', '2026-09-13 00:00:00', '2026-09-13 00:00:00', 2003, 2, 95, 'Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-08-r0', 'pqs2-08', 'Lula', 'PT', 42, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-08-r1', 'pqs2-08', 'Flávio Bolsonaro', 'PL', 37, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-08-r2', 'pqs2-08', 'Augusto Cury', 'AVANTE', 6, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-08-r3', 'pqs2-08', 'Ronaldo Caiado', 'PSD', 5, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-08-r4', 'pqs2-08', 'Renan Santos', 'MISSÃO', 2, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-08-r5', 'pqs2-08', 'Indecisos/Brancos', NULL, 6, 5);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-09', 'Presidente', 2, 'estimulada', 'Flávio Bolsonaro x Lula', 'Datafolha', NULL, '2026-09-08 00:00:00', '2026-09-11 00:00:00', '2026-09-11 00:00:00', 2002, 2, 95, 'Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-09-r0', 'pqs2-09', 'Lula', 'PT', 46, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-09-r1', 'pqs2-09', 'Flávio Bolsonaro', 'PL', 44, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-09-r2', 'pqs2-09', 'Indecisos/Brancos', NULL, 10, 2);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-10', 'Presidente', 2, 'estimulada', 'Flávio Bolsonaro x Lula', 'Genial/Quaest', NULL, '2026-09-10 00:00:00', '2026-09-13 00:00:00', '2026-09-13 00:00:00', 2004, 2, 95, 'Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-10-r0', 'pqs2-10', 'Flávio Bolsonaro', 'PL', 42, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-10-r1', 'pqs2-10', 'Lula', 'PT', 40, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-10-r2', 'pqs2-10', 'Indecisos/Brancos', NULL, 18, 2);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs2-11', 'Presidente', 2, 'estimulada', 'Flávio Bolsonaro x Lula', 'Nexus/BTG Pactual', NULL, '2026-09-11 00:00:00', '2026-09-13 00:00:00', '2026-09-13 00:00:00', 2003, 2, 95, 'Data exibida = fim do campo. Carga automática 15/09/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-11-r0', 'pqs2-11', 'Lula', 'PT', 47, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-11-r1', 'pqs2-11', 'Flávio Bolsonaro', 'PL', 46, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs2-11-r2', 'pqs2-11', 'Indecisos/Brancos', NULL, 7, 2);
