-- Seed: reta final — 4 pesquisas PA (Futura/100% Cidades, Ampla, Doxa, RTBD) + Vox e Datafolha presidenciais
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-01', 'Governador', 1, 'estimulada', NULL, 'Futura/100% Cidades', NULL, '2026-09-24 00:00:00', '2026-09-28 00:00:00', '2026-10-01 00:00:00', 1008, 3.1, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-01-r0', 'pqs8-01', 'Daniel Santos', 'PODE', 49.9, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-01-r1', 'pqs8-01', 'Hana Ghassan', 'MDB', 38.6, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-01-r2', 'pqs8-01', 'Araceli Lemos', 'PSOL', 2.5, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-01-r3', 'pqs8-01', 'Outros', NULL, 0.9, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-01-r4', 'pqs8-01', 'Brancos/Nulos', NULL, 2.9, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-01-r5', 'pqs8-01', 'Não sabe', NULL, 5.1, 5);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-02', 'Governador', 2, 'estimulada', 'Hana Ghassan x Daniel Santos', 'Futura/100% Cidades', NULL, '2026-09-24 00:00:00', '2026-09-28 00:00:00', '2026-10-01 00:00:00', 1008, 3.1, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-02-r0', 'pqs8-02', 'Daniel Santos', 'PODE', 52.4, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-02-r1', 'pqs8-02', 'Hana Ghassan', 'MDB', 41.6, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-02-r2', 'pqs8-02', 'Brancos/Nulos', NULL, 3, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-02-r3', 'pqs8-02', 'Não sabe', NULL, 3, 3);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-03', 'Senador', 1, 'estimulada', NULL, 'Futura/100% Cidades', NULL, '2026-09-24 00:00:00', '2026-09-28 00:00:00', '2026-10-01 00:00:00', 1008, 3.1, 95, 'Disputa por 2 vagas — consolidado dos dois votos (soma passa de 100%). Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r0', 'pqs8-03', 'Helder Barbalho', 'MDB', 48.5, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r1', 'pqs8-03', 'Éder Mauro', 'PL', 39.1, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r2', 'pqs8-03', 'Chicão Melo', 'UNIÃO', 35.2, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r3', 'pqs8-03', 'Zequinha Marinho', 'PODE', 27.3, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r4', 'pqs8-03', 'Celso Sabino', 'PDT', 12.3, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r5', 'pqs8-03', 'Coronel Jonildo', 'DC', 2.9, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r6', 'pqs8-03', 'Gizelle Freitas', 'PSOL', 2.2, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r7', 'pqs8-03', 'Lívia Noronha', 'SOLIDARIEDADE', 1.6, 7);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-03-r8', 'pqs8-03', 'Não sabe/Brancos', NULL, 28.2, 8);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-04', 'Governador', 1, 'estimulada', NULL, 'Ampla', NULL, '2026-09-24 00:00:00', '2026-09-28 00:00:00', '2026-09-30 00:00:00', 1500, 2.6, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-04-r0', 'pqs8-04', 'Daniel Santos', 'PODE', 43.3, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-04-r1', 'pqs8-04', 'Hana Ghassan', 'MDB', 33, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-04-r2', 'pqs8-04', 'Araceli Lemos', 'PSOL', 2.1, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-04-r3', 'pqs8-04', 'Outros', NULL, 1.6, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-04-r4', 'pqs8-04', 'Brancos/Nulos', NULL, 6.7, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-04-r5', 'pqs8-04', 'Não sabe', NULL, 13.3, 5);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-05', 'Governador', 2, 'estimulada', 'Hana Ghassan x Daniel Santos', 'Ampla', NULL, '2026-09-24 00:00:00', '2026-09-28 00:00:00', '2026-09-30 00:00:00', 1500, 2.6, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-05-r0', 'pqs8-05', 'Daniel Santos', 'PODE', 48.4, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-05-r1', 'pqs8-05', 'Hana Ghassan', 'MDB', 36.8, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-05-r2', 'pqs8-05', 'Brancos/Nulos', NULL, 4.3, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-05-r3', 'pqs8-05', 'Não sabe', NULL, 10.5, 3);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-06', 'Governador', 1, 'estimulada', NULL, 'Doxa', NULL, '2026-09-24 00:00:00', '2026-09-28 00:00:00', '2026-09-30 00:00:00', 2000, 2.2, 95, 'Única da reta final com Hana à frente. Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-06-r0', 'pqs8-06', 'Hana Ghassan', 'MDB', 43.3, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-06-r1', 'pqs8-06', 'Daniel Santos', 'PODE', 36.8, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-06-r2', 'pqs8-06', 'Araceli Lemos', 'PSOL', 1, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-06-r3', 'pqs8-06', 'Outros', NULL, 1.3, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-06-r4', 'pqs8-06', 'Brancos/Nulos', NULL, 4.7, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-06-r5', 'pqs8-06', 'Não sabe', NULL, 12.9, 5);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-07', 'Governador', 2, 'estimulada', 'Hana Ghassan x Daniel Santos', 'Doxa', NULL, '2026-09-24 00:00:00', '2026-09-28 00:00:00', '2026-09-30 00:00:00', 2000, 2.2, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-07-r0', 'pqs8-07', 'Hana Ghassan', 'MDB', 47.8, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-07-r1', 'pqs8-07', 'Daniel Santos', 'PODE', 42.2, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-07-r2', 'pqs8-07', 'Brancos/Nulos', NULL, 5, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-07-r3', 'pqs8-07', 'Não sabe', NULL, 5, 3);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-08', 'Senador', 1, 'estimulada', NULL, 'Doxa', NULL, '2026-09-24 00:00:00', '2026-09-28 00:00:00', '2026-09-30 00:00:00', 2000, 2.2, 95, 'Voto único estimulado. Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-08-r0', 'pqs8-08', 'Helder Barbalho', 'MDB', 23.51, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-08-r1', 'pqs8-08', 'Éder Mauro', 'PL', 16.78, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-08-r2', 'pqs8-08', 'Chicão Melo', 'UNIÃO', 16.1, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-08-r3', 'pqs8-08', 'Zequinha Marinho', 'PODE', 10.86, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-08-r4', 'pqs8-08', 'Celso Sabino', 'PDT', 9.8, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-08-r5', 'pqs8-08', 'Lívia Noronha', 'SOLIDARIEDADE', 1.31, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-08-r6', 'pqs8-08', 'Brancos/Nulos', NULL, 5.79, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-08-r7', 'pqs8-08', 'Não sabe', NULL, 12.8, 7);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-09', 'Governador', 1, 'estimulada', NULL, 'Real Time Big Data', NULL, '2026-09-23 00:00:00', '2026-09-26 00:00:00', '2026-09-28 00:00:00', 1600, 2, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-09-r0', 'pqs8-09', 'Hana Ghassan', 'MDB', 44, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-09-r1', 'pqs8-09', 'Daniel Santos', 'PODE', 37, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-09-r2', 'pqs8-09', 'Araceli Lemos', 'PSOL', 2, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-09-r3', 'pqs8-09', 'Brancos/Nulos', NULL, 9, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-09-r4', 'pqs8-09', 'Não sabe', NULL, 7, 4);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-10', 'Governador', 2, 'estimulada', 'Hana Ghassan x Daniel Santos', 'Real Time Big Data', NULL, '2026-09-23 00:00:00', '2026-09-26 00:00:00', '2026-09-28 00:00:00', 1600, 2, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-10-r0', 'pqs8-10', 'Hana Ghassan', 'MDB', 45, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-10-r1', 'pqs8-10', 'Daniel Santos', 'PODE', 37, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-10-r2', 'pqs8-10', 'Brancos/Nulos', NULL, 8, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-10-r3', 'pqs8-10', 'Não sabe', NULL, 10, 3);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-11', 'Senador', 1, 'estimulada', NULL, 'Real Time Big Data', NULL, '2026-09-23 00:00:00', '2026-09-26 00:00:00', '2026-09-28 00:00:00', 1600, 2, 95, 'Disputa por 2 vagas. Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r0', 'pqs8-11', 'Helder Barbalho', 'MDB', 36, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r1', 'pqs8-11', 'Éder Mauro', 'PL', 16, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r2', 'pqs8-11', 'Chicão Melo', 'UNIÃO', 16, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r3', 'pqs8-11', 'Zequinha Marinho', 'PODE', 13, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r4', 'pqs8-11', 'Celso Sabino', 'PDT', 10, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r5', 'pqs8-11', 'Lívia Noronha', 'SOLIDARIEDADE', 3, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r6', 'pqs8-11', 'Gizelle Freitas', 'PSOL', 1, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r7', 'pqs8-11', 'Conti', 'PSOL', 1, 7);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r8', 'pqs8-11', 'Brancos/Nulos', NULL, 2, 8);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-11-r9', 'pqs8-11', 'Não sabe', NULL, 3, 9);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-12', 'Presidente', 1, 'estimulada', NULL, 'Vox Brasil', NULL, '2026-09-29 00:00:00', '2026-10-01 00:00:00', '2026-10-02 00:00:00', 2100, 2.15, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-12-r0', 'pqs8-12', 'Flávio Bolsonaro', 'PL', 41.2, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-12-r1', 'pqs8-12', 'Lula', 'PT', 40.4, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-12-r2', 'pqs8-12', 'Renan Santos', 'MISSÃO', 3.3, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-12-r3', 'pqs8-12', 'Ronaldo Caiado', 'PSD', 2.2, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-12-r4', 'pqs8-12', 'Romeu Zema', 'NOVO', 1.3, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-12-r5', 'pqs8-12', 'Augusto Cury', 'AVANTE', 1.2, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-12-r6', 'pqs8-12', 'Não sabe', NULL, 10.2, 6);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-13', 'Presidente', 2, 'estimulada', 'Lula x Flávio Bolsonaro', 'Vox Brasil', NULL, '2026-09-29 00:00:00', '2026-10-01 00:00:00', '2026-10-02 00:00:00', 2100, 2.15, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-13-r0', 'pqs8-13', 'Flávio Bolsonaro', 'PL', 48.2, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-13-r1', 'pqs8-13', 'Lula', 'PT', 45.2, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-13-r2', 'pqs8-13', 'Brancos/Nulos e não sabem', NULL, 6.6, 2);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-14', 'Presidente', 1, 'estimulada', NULL, 'Datafolha', NULL, '2026-09-28 00:00:00', '2026-10-01 00:00:00', '2026-10-01 00:00:00', 2506, 2, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-14-r0', 'pqs8-14', 'Lula', 'PT', 42, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-14-r1', 'pqs8-14', 'Flávio Bolsonaro', 'PL', 38, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-14-r2', 'pqs8-14', 'Augusto Cury', 'AVANTE', 4, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-14-r3', 'pqs8-14', 'Renan Santos', 'MISSÃO', 3, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-14-r4', 'pqs8-14', 'Ronaldo Caiado', 'PSD', 3, 4);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-14-r5', 'pqs8-14', 'Romeu Zema', 'NOVO', 1, 5);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-14-r6', 'pqs8-14', 'Samara Martins', 'UP', 1, 6);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-14-r7', 'pqs8-14', 'Não sabe', NULL, 7, 7);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqs8-15', 'Presidente', 2, 'estimulada', 'Lula x Flávio Bolsonaro', 'Datafolha', NULL, '2026-09-28 00:00:00', '2026-10-01 00:00:00', '2026-10-01 00:00:00', 2506, 2, 95, 'Data exibida = fim do campo. Carga automática 02/10/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-15-r0', 'pqs8-15', 'Lula', 'PT', 48, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-15-r1', 'pqs8-15', 'Flávio Bolsonaro', 'PL', 45, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqs8-15-r2', 'pqs8-15', 'Brancos/Nulos e não sabem', NULL, 7, 2);
