-- Seed: Verita ago/2026 (Gov PA validos, Senador PA, Presidente 2o turno)
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqver-01', 'Governador', 1, 'estimulada', NULL, 'Veritá', 'PA-04167/2026', '2026-08-19 00:00:00', '2026-08-23 00:00:00', '2026-08-23 00:00:00', 1525, 2.5, 95, 'Percentuais sobre VOTOS VÁLIDOS (excluem brancos/nulos/indecisos) — padrão do instituto, não comparável direto com pesquisas de % total. Data exibida = fim do campo. Carga automática 25/08/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-01-r0', 'pqver-01', 'Daniel Santos', 'PODE', 49.7, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-01-r1', 'pqver-01', 'Hana Ghassan', 'MDB', 41.4, 1);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqver-02', 'Senador', 1, 'estimulada', NULL, 'Veritá', 'PA-04167/2026', '2026-08-19 00:00:00', '2026-08-23 00:00:00', '2026-08-23 00:00:00', 1525, 2.5, 95, 'Consolidação dos dois votos (% de casos), sobre votos válidos. Disputa por 2 vagas. Data exibida = fim do campo. Carga automática 25/08/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-02-r0', 'pqver-02', 'Éder Mauro', 'PL', 36.3, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-02-r1', 'pqver-02', 'Helder Barbalho', 'MDB', 25, 1);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-02-r2', 'pqver-02', 'Celso Sabino', 'PDT', 15.7, 2);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-02-r3', 'pqver-02', 'Zequinha Marinho', 'PODE', 14.7, 3);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-02-r4', 'pqver-02', 'Chicão Melo', 'UNIÃO', 12.5, 4);
INSERT INTO "PesquisaEleitoral" (id, disputa, turno, tipo, cenario, instituto, registroTSE, dataCampoInicio, dataCampoFim, dataDivulgacao, amostra, margemErro, confianca, observacoes, createdAt, updatedAt) VALUES ('pqver-03', 'Presidente', 2, 'estimulada', 'Flávio Bolsonaro x Lula', 'Veritá', 'BR-07588/2026', '2026-08-16 00:00:00', '2026-08-20 00:00:00', '2026-08-20 00:00:00', 3840, 2, 95, 'Cenário de 2º turno da rodada nacional Veritá. Data exibida = fim do campo. Carga automática 25/08/2026.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-03-r0', 'pqver-03', 'Flávio Bolsonaro', 'PL', 47.3, 0);
INSERT INTO "PesquisaResultado" (id, pesquisaId, nome, partido, percentual, ordem) VALUES ('pqver-03-r1', 'pqver-03', 'Lula', 'PT', 42, 1);
